apiVersion: apps/v1
kind: Deployment
metadata:
  name: c9idev2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud9-v2
  template:
    metadata:
      labels:
        app: cloud9-v2
    spec:
      containers:
      - name: cloud9-v2
        image: chinodesuuu/c9:v2
        securityContext:
          runAsUser: 1000
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "2048Mi"
        env:
        - name: PLN_USERNAME
          value: "override"
        - name: PLN_PASSWORD
          value: "this"
---
kind: Service
apiVersion: v1
metadata:
  name: cloud9-v2
spec:
  ports:
  - name: http
    port: 8181
  selector:
    app: cloud9-v2