apiVersion: apps/v1
kind: Deployment
metadata:
  name: c9idev2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud9-v2
  template:
    metadata:
      labels:
        pod.staroid.com/isolation: dedicated
        pod.staroid.com/instance-type: standard-2
        app: cloud9-v2
    spec:
      containers:
      - name: cloud9-v2
        image: chinodesuuu/c9:v2
        securityContext:
          runAsUser: 1000
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "2048Mi"
        volumeMounts:
          - name: workspace-pvc
            mountPath: /workspace
        env:
        - name: PLN_USERNAME
          value: "override"
        - name: PLN_PASSWORD
          value: "this"
      volumes:
      - name: workspace-pvc
        persistentVolumeClaim:
          claimName: workspace-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: cloud9-v2
spec:
  ports:
  - name: http
    port: 8181
  selector:
    app: cloud9-v2
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workspace-pvc
  annotations:
    storage.staroid.com/scope: Instance
spec:
  storageClassName: ssd
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
